In [16]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [27]:
file_name = "/content/drive/MyDrive/Colab Notebooks/Questionnaire For non Mobile App Users (Responses).si.en.xlsx"
sheet =  "Form responses 1"

import pandas as pd
dataset = pd.read_excel(io=file_name, sheet_name=sheet)
print(dataset.head(5))  # print first 5 rows of the dataframe

                Timestamp  ... What kind of financial services do you want to see through your mobile phone - Debt Management
0 2020-11-02 15:32:11.395  ...                                                4.0                                            
1 2020-11-02 15:33:52.735  ...                                                1.0                                            
2 2020-11-02 15:36:05.548  ...                                                5.0                                            
3 2020-11-02 15:42:37.935  ...                                                5.0                                            
4 2020-11-02 15:46:50.137  ...                                                5.0                                            

[5 rows x 26 columns]


In [28]:
dataset_table=pd.crosstab(dataset['Degree non degree'],dataset['Do you use mobile app for banking'])
print(dataset_table)

Do you use mobile app for banking  No  Yes
Degree non degree                         
No                                 46   12
Yes                                11   37


In [29]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[46 12]
 [11 37]]


In [31]:
val=stats.chi2_contingency(dataset_table)
val

(31.37161381491495,
 2.130734281471284e-08,
 1,
 array([[31.18867925, 26.81132075],
        [25.81132075, 22.18867925]]))

In [32]:
Expected_Values=val[3]
print(Expected_Values)

[[31.18867925 26.81132075]
 [25.81132075 22.18867925]]


In [33]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [34]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 33.60199040293673


In [35]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [36]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 6.762349458178107e-09
Significance level:  0.05
Degree of Freedom:  1
p-value: 6.762349458178107e-09


In [37]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
Reject H0,There is a relationship between 2 categorical variables
